# Generated by Django 4.2.4 on 2023-08-25 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='artivle',
            new_name='article',
        ),
    ]
